language: go
sudo: false
matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: 1.x
    - go: master
  allow_failures:
    - go: master

  before_install:
   - go get github.com/tools/godep

  install:
    - godep restore
  
  script: 
    - make